Add Vienna.
coderetreat/coderetreat.org pull request #712
Opened 2020-10-21 18:49 UTC by codecop

2020-10-22 13:50 UTC, rradczewski requested changes

2020-10-22 13:50 UTC, rradczewski commented on _data/events/virtual-2020-11-07-coderetreat-gdcr-2020-vienna-remote.json
> +  "sponsors": [
Should be left empty (`[]`)

2020-10-22 13:50 UTC, rradczewski commented on _data/events/virtual-2020-11-07-coderetreat-gdcr-2020-vienna-remote.json
> +  "moderators": [
Should be left empty (`[]`)

2020-10-22 17:38 UTC, codecop commented
Done

2020-10-22 21:30 UTC, merged

2020-11-13 08:11 UTC, rradczewski commented
Hi, we hope you had a great Global Day Of Coderetreat! We're trying to understand how the current situation has affected the events this year and how we could support you next year for #GDCR2021.

For this purpose, we created [a seven-questions-survey](https://docs.google.com/forms/d/e/1FAIpQLSdi8fmw42s8tXtVneJH5VcRpB9vMf35gJ2APw4PijQ0-Gq_Ww/viewform?usp=sf_link) (anonymously, all optional, single page) for those who organized an event this year. It would help us tremendously if you could fill it out. It doesn't take long, promise :smile: 

Thanks and all the best,
Raimo